execution_env=local 
#enable system local enviorment
#execution_env=remote
#enable system on remote enviroment

appURL=https://tutorialsninja.com/demo/
Email=chaitaliasutkar@gmail.com
Password=Bpa572001@

SearchKeyword=iphone